apiVersion: v1
kind: Namespace
metadata:
  name: kuma-demo4
  namespace: kuma-demo4
  annotations:
    kuma.io/sidecar-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-deployment-new
  name: spring-deployment-new-service
  namespace: kuma-demo4
  annotations:
    80.service.kuma.io/protocol: "http"
    ingress.kubernetes.io/service-upstream: "true"
spec:
  ports:
    - port: 8085
      protocol: TCP
      targetPort: 8085
  selector:
    app: spring-deployment-new
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-deployment-new
  name: spring-deployment-new-deployment
  namespace: kuma-demo4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-deployment-new
      version: v0
  strategy: {}
  template:
    metadata:
      labels:
        app: spring-deployment-new
        version: v0
    spec:
      containers:
      - image: jaikratsingh/spring-boot-k8s:v7
        name: spring-boot-k8s
        #ports: #for AWS
        # - containerPort: 8080 #for aws
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment-new-deployment-v1
  namespace: kuma-demo4
spec:
  replicas: 0
  selector:
    matchLabels:
      app: spring-deployment-new
      version: v1
  strategy: {}
  template:
    metadata:
      labels:
        app: spring-deployment-new
        version: v1
    spec:
      containers:
        - image: jaikratsingh/spring-boot-k8s:v8
          name: spring-boot-k8s
          resources: {}