apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: general-traffic
  namespace: kuma-demo7
spec:
  sources:
    - match:
        kuma.io/service: kong-proxy_kuma-gateway_svc_80
  destinations:
    - match:
        kuma.io/service: spring-deployment-new-service_kuma-demo7_svc_8085
  conf:
    destination:
      kuma.io/service: spring-deployment-new-service_kuma-demo7_svc_8085
      version: v0
#    loadBalancer:
#      roundRobin: { }
#    destination:
#      kuma.io/service: '*'