apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  name: split-traffic
  namespace: kuma-demo4
spec:
  sources:
    - match:
        kuma.io/service: kong-proxy_kuma-gateway_svc_80
  destinations:
    - match:
        kuma.io/service: spring-deployment-new-service_kuma-demo4_svc_8085
  conf:
    split:
      - weight: 10
        destination:
          kuma.io/service: spring-deployment-new-service_kuma-demo4_svc_8085
          version: 'v0'
      - weight: 90
        destination:
          kuma.io/service: spring-deployment-new-service_kuma-demo4_svc_8085
          version: 'v1'
#    loadBalancer:
#      roundRobin: { }
#    destination:
#      kuma.io/service: '*'