apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  name: spring-boot-traffic-rules
  namespace: kuma-demo7
spec:
  sources:
    - match:
        kuma.io/service: kong-proxy_kuma-gateway_svc_80
  destinations:
    - match:
        kuma.io/service: spring-deployment-new-service_kuma-demo7_svc_8085